In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

In [2]:
# filters = torch.randn(1, 5, 3, 3) #(no. of kernels, channel, width, height)
inputs = torch.randn(1, 5, 32, 32)  #(batch size, channels, width, heights)
padding = 1
stride = 1

## Output using Conv2d (torch)

In [115]:
output = F.conv2d(inputs, filters, padding=padding, stride=stride)

In [116]:
output.shape

torch.Size([1, 8, 7, 7])

## Output using the Function

In [117]:
def output_size(p,s,inputs,filters):
    output_width = (inputs.shape[2] - filters.shape[2] + (2*p))/s + 1
    output_heights = (inputs.shape[3] - filters.shape[3] + (2*p))/s + 1
    output_dimension = [inputs.shape[0],filters.shape[0], int(output_width), int(output_heights)]
    return output_dimension

In [118]:
output_dimension = output_size(padding, stride, inputs, filters)
output_dimension

[1, 8, 7, 7]

In [42]:
inputs = torch.randn(1, 5, 5, 5)#(batch size, channels, width, heights)
filters = torch.randn(1, 5, 3, 3)
padding = 0
stride = 1
k_s = [3,3]

In [47]:
s = torch.nn.functional.unfold(inputs, kernel_size = [3,3], dilation=1, padding=padding, stride=stride)

In [48]:
s.shape

torch.Size([1, 45, 9])

In [49]:
s

tensor([[[-1.1298e+00,  1.4868e+00, -1.0933e-01,  6.8532e-01, -1.5469e-01,
          -1.4652e+00, -6.0913e-01, -6.4593e-02, -8.0309e-01],
         [ 1.4868e+00, -1.0933e-01, -1.9765e+00, -1.5469e-01, -1.4652e+00,
           8.7685e-01, -6.4593e-02, -8.0309e-01,  1.6058e+00],
         [-1.0933e-01, -1.9765e+00, -1.5587e+00, -1.4652e+00,  8.7685e-01,
           6.3514e-01, -8.0309e-01,  1.6058e+00, -8.2907e-02],
         [ 6.8532e-01, -1.5469e-01, -1.4652e+00, -6.0913e-01, -6.4593e-02,
          -8.0309e-01,  1.0250e+00, -9.9820e-01,  6.0193e-01],
         [-1.5469e-01, -1.4652e+00,  8.7685e-01, -6.4593e-02, -8.0309e-01,
           1.6058e+00, -9.9820e-01,  6.0193e-01,  6.2682e-01],
         [-1.4652e+00,  8.7685e-01,  6.3514e-01, -8.0309e-01,  1.6058e+00,
          -8.2907e-02,  6.0193e-01,  6.2682e-01, -3.3753e-01],
         [-6.0913e-01, -6.4593e-02, -8.0309e-01,  1.0250e+00, -9.9820e-01,
           6.0193e-01,  5.5191e-01,  1.1035e+00, -4.6258e-01],
         [-6.4593e-02, -8.0309e-01

In [74]:
filters.flatten()

tensor([-0.4314, -1.3042,  0.1276,  1.7879, -2.1044, -0.7346, -1.0459,  0.1640,
        -0.3593, -1.6879, -0.2109,  0.0375,  0.1512, -1.2878,  0.2334,  0.4233,
         0.9969, -0.8263, -0.0512,  0.7856, -0.4701,  0.3592,  0.8320, -0.2684,
        -1.1288, -0.0619, -1.1760,  0.7305, -0.8542, -0.2573,  1.0129,  1.1170,
         1.1006, -1.5316,  0.3633,  0.5063,  1.6942,  0.9849,  0.1757,  0.2054,
        -0.1789,  0.8944,  0.6079, -0.2367, -0.9503])

In [55]:
inputs

tensor([[[[-1.1298e+00,  1.4868e+00, -1.0933e-01, -1.9765e+00, -1.5587e+00],
          [ 6.8532e-01, -1.5469e-01, -1.4652e+00,  8.7685e-01,  6.3514e-01],
          [-6.0913e-01, -6.4593e-02, -8.0309e-01,  1.6058e+00, -8.2907e-02],
          [ 1.0250e+00, -9.9820e-01,  6.0193e-01,  6.2682e-01, -3.3753e-01],
          [ 5.5191e-01,  1.1035e+00, -4.6258e-01, -5.0647e-01, -1.0259e+00]],

         [[-3.7195e-01, -1.0139e+00, -8.7511e-01,  8.6801e-01, -1.2700e+00],
          [ 2.0566e-01, -9.8086e-01, -2.0996e+00, -1.4794e+00, -1.7332e+00],
          [-4.0915e-01, -1.5217e-01, -3.0485e-01, -8.2510e-01,  1.3495e+00],
          [ 8.0401e-01,  3.4483e-01, -5.2574e-01, -1.9420e-01,  1.8075e+00],
          [-1.6589e+00,  8.2332e-02, -1.4327e+00, -9.1177e-01,  1.4112e+00]],

         [[-3.7333e-01, -6.9088e-01,  3.8221e-01,  2.7724e-02, -4.6934e-01],
          [ 1.8835e+00,  4.8320e-01,  2.3748e-01,  3.0278e-01,  1.5685e+00],
          [ 1.7464e+00,  1.8300e+00,  3.4281e-02,  1.6230e+00,  7.6258e-

In [106]:
inputs_new = np.pad(inputs, pad_width = ((0,0),(0,0),(1, 1), (1, 1)))

In [107]:
inputs_new

array([[[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00],
         [ 0.0000000e+00, -1.1297834e+00,  1.4868010e+00,
          -1.0933190e-01, -1.9764681e+00, -1.5587034e+00,
           0.0000000e+00],
         [ 0.0000000e+00,  6.8532020e-01, -1.5468623e-01,
          -1.4651884e+00,  8.7684685e-01,  6.3514006e-01,
           0.0000000e+00],
         [ 0.0000000e+00, -6.0912687e-01, -6.4592995e-02,
          -8.0309069e-01,  1.6057577e+00, -8.2907416e-02,
           0.0000000e+00],
         [ 0.0000000e+00,  1.0250096e+00, -9.9819738e-01,
           6.0193235e-01,  6.2682080e-01, -3.3752578e-01,
           0.0000000e+00],
         [ 0.0000000e+00,  5.5191022e-01,  1.1035016e+00,
          -4.6257722e-01, -5.0646549e-01, -1.0259041e+00,
           0.0000000e+00],
         [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
           0.0000000e+00]]

In [56]:
inputs.shape

torch.Size([1, 5, 5, 5])

In [108]:
patches = []
vec_y = []
p1 = int(((inputs.shape[2] + (2*padding) - k_s[0])/stride) +1)
p2 = int(((inputs.shape[3] + (2*padding) - k_s[1])/stride) +1)
p = p1*p2
counter=0 
temp = []
inputs = np.pad(inputs, pad_width = ((0,0),(0,0),(padding,padding),(padding,padding)))
for b in range(inputs.shape[0]):
    for c in range(inputs.shape[1]): 
        for h in range(0,inputs.shape[2],stride):
            for w in range(0,inputs.shape[3],stride):
                vec_x = inputs[b][c][h:k_s[0]+h,:][:,w:k_s[1]+w]
                if (vec_x.shape[0]==k_s[0] & vec_x.shape[1]==k_s[1]):
                    vec_x = vec_x.flatten()
                    patches.append(vec_x)  

In [ ]:
Y = X(patches) (45*9) * W (1*45)
reshape Y (1,45,9)

In [109]:
patches

[array([ 0.        ,  0.        ,  0.        ,  0.        , -1.1297834 ,
         1.486801  ,  0.        ,  0.6853202 , -0.15468623], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , -1.1297834 ,  1.486801  ,
        -0.1093319 ,  0.6853202 , -0.15468623, -1.4651884 ], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  1.486801  , -0.1093319 ,
        -1.9764681 , -0.15468623, -1.4651884 ,  0.87684685], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , -0.1093319 , -1.9764681 ,
        -1.5587034 , -1.4651884 ,  0.87684685,  0.63514006], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , -1.9764681 , -1.5587034 ,
         0.        ,  0.87684685,  0.63514006,  0.        ], dtype=float32),
 array([ 0.        , -1.1297834 ,  1.486801  ,  0.        ,  0.6853202 ,
        -0.15468623,  0.        , -0.60912687, -0.06459299], dtype=float32),
 array([-1.1297834 ,  1.486801  , -0.1093319 ,  0.6853202 , -0.15468623,
        -1.4651884 , -0.609

In [37]:
vec_y

[[-2.5151942, 5.8089266, 6.2895603, -3.7167773],
 [-2.1399696, 3.8169336, 2.2439618, -0.5011886],
 [0.20494875, -0.089832485, 0.55324876, -8.468789],
 [-2.5067632, -2.3658807, 0.10278562, 3.8137016],
 [-1.2657555, -2.9381158, -0.1503638, 0.67146647]]

In [10]:
len(patches)

20

In [10]:
vec_y_ = [sum(l) for l in zip(*vec_y)]
vec_y_

[-1.1125056743621826,
 -0.6539099216461182,
 11.942612648010254,
 -0.36211347579956055]

In [11]:
patches

[tensor([ 0.9455, -1.6302, -0.2969, -0.5051, -0.7822,  1.2030, -0.9648,  0.3182,
          0.1177]),
 tensor([-0.2969, -1.2051,  0.3804,  1.2030, -0.3503,  0.2954,  0.1177,  0.7444,
         -2.0276]),
 tensor([-0.9648,  0.3182,  0.1177,  0.7682, -0.6916,  0.4217,  2.1595, -1.5755,
          1.7651]),
 tensor([ 0.1177,  0.7444, -2.0276,  0.4217, -1.6635, -0.3099,  1.7651,  0.3005,
         -1.7633]),
 tensor([-0.9387, -1.5933,  1.1931,  0.8191, -1.4373, -1.1525,  0.3386, -0.0586,
         -1.5014]),
 tensor([ 1.1931,  0.4996, -0.5301, -1.1525,  0.0101, -1.6101, -1.5014,  0.2772,
          0.9790]),
 tensor([ 0.3386, -0.0586, -1.5014,  1.4353, -1.4882, -1.7622,  0.1270, -0.1154,
         -0.2983]),
 tensor([-1.5014,  0.2772,  0.9790, -1.7622, -0.2944, -0.2947, -0.2983, -0.7257,
         -0.9351]),
 tensor([ 0.4218,  1.1298, -0.5958, -0.4476,  0.4573,  0.3174,  0.7056, -1.2068,
         -0.1514]),
 tensor([-0.5958,  0.1154, -0.3100,  0.3174,  0.6046,  0.9260, -0.1514,  0.0066,
         -

In [100]:
vec_y

tensor([[[[-2.3777,  0.0398, -0.1287],
          [ 0.1192,  0.1568, -1.4522],
          [-1.3175,  1.6563, -0.2969]],

         [[ 1.1663, -2.2362, -1.0640],
          [ 1.6873, -2.0690,  0.2811],
          [ 2.3326, -1.6964, -0.2927]],

         [[-0.4059, -0.9411, -2.3565],
          [ 0.7229,  1.8135, -0.2406],
          [ 0.9247, -2.1627, -0.7697]],

         [[-1.8000,  0.4094, -1.9705],
          [-0.1096,  0.9815,  0.5418],
          [ 0.9149,  0.9857, -2.2941]],

         [[ 0.2226, -0.2236,  0.3334],
          [-1.3291,  1.4324,  2.4265],
          [-0.3209,  1.7472, -0.7581]]]])

In [99]:
filters

tensor([[[[ 2.0590, -0.0344,  0.1115],
          [-0.1032, -0.1357,  1.2576],
          [ 1.1409, -1.4343,  0.2571]],

         [[-1.0100,  1.9365,  0.9214],
          [-1.4611,  1.7917, -0.2435],
          [-2.0200,  1.4691,  0.2535]],

         [[ 0.3515,  0.8150,  2.0406],
          [-0.6260, -1.5705,  0.2083],
          [-0.8008,  1.8729,  0.6665]],

         [[ 1.5588, -0.3545,  1.7064],
          [ 0.0949, -0.8500, -0.4692],
          [-0.7923, -0.8536,  1.9867]],

         [[-0.1928,  0.1937, -0.2887],
          [ 1.1509, -1.2404, -2.1013],
          [ 0.2779, -1.5130,  0.6565]]]])

In [93]:
patches

[tensor([ 1.1623,  0.0990,  0.0676, -0.0239,  1.5049, -1.6149,  0.9565, -0.9746,
         -0.0314]),
 tensor([ 0.0676, -0.5342,  1.0319, -1.6149,  0.2436,  1.3327, -0.0314, -0.2917,
         -1.2974]),
 tensor([ 0.9565, -0.9746, -0.0314, -0.8228, -0.3060,  0.6507,  1.1243, -0.5989,
          0.6456]),
 tensor([-0.0314, -0.2917, -1.2974,  0.6507, -0.5405,  0.1651,  0.6456,  1.8070,
         -1.1815]),
 tensor([-1.8482,  0.1446,  0.1366,  0.1223,  1.3679,  1.1363,  0.3160,  0.1314,
          0.9522]),
 tensor([ 0.1366, -0.8422,  0.9538,  1.1363,  0.1184, -0.2462,  0.9522,  1.5645,
         -1.3031]),
 tensor([ 0.3160,  0.1314,  0.9522, -0.1971, -0.1954, -0.9696, -0.6717, -0.6264,
         -0.8904]),
 tensor([ 0.9522,  1.5645, -1.3031, -0.9696,  0.7667,  0.5462, -0.8904, -0.7356,
          1.0093]),
 tensor([ 0.6560, -2.1913, -1.4444,  2.3151,  0.6570, -0.2937,  1.0366,  0.1147,
         -0.6527]),
 tensor([-1.4444,  1.6316, -0.7270, -0.2937,  0.9959,  0.6168, -0.6527,  0.5959,
          

In [179]:
inputs = torch.randn(1, 5, 32, 32)#(batch size, channels, width, heights)
filters = torch.randn(1, 5, 3, 3)
padding = 1
stride = 1
k_s = [3,3]

In [180]:
s = torch.nn.functional.unfold(inputs, kernel_size = [3,3], dilation=1, padding=padding, stride=stride)

In [181]:
s.shape

torch.Size([1, 45, 1024])

In [185]:
len(s[0][0])

1024

In [186]:
s

tensor([[[ 0.0000,  0.0000,  0.0000,  ..., -0.0602, -1.7722,  0.3555],
         [ 0.0000,  0.0000,  0.0000,  ..., -1.7722,  0.3555,  2.3754],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.3555,  2.3754,  0.0000],
         ...,
         [ 0.0000,  0.6248, -0.6687,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.6248, -0.6687,  1.9227,  ...,  0.0000,  0.0000,  0.0000],
         [-0.6687,  1.9227,  1.4823,  ...,  0.0000,  0.0000,  0.0000]]])